export const routes = {
  dashboard: {
    main: '/dashboard',
    material: '/dashboard/material',
    product: '/dashboard/product',
    store: '/dashboard/store',
    data: '/dashboard/data',
    categories: '/dashboard/categories',
    users: '/dashboard/users',
    // editShipment: (id: string) => `/logistics/shipments/${id}/edit`,
    // shipmentDetails: (id: string) => `/logistics/shipments/${id}`,
    // tracking: (id: string) => `/logistics/tracking/${id}`,
  },
  forms: {
    profileSettings: '/forms/profile-settings',
    notificationPreference: '/forms/profile-settings/notification',
    personalInformation: '/forms/profile-settings/profile',
    newsletter: '/forms/newsletter',
  },
  profile: '/profile',
  
  searchAndFilter: {
    realEstate: '/search/real-estate',
    nft: '/search/nft',
    flight: '/search/flight',
  },
  support: {
    dashboard: '/support',
    inbox: '/support/inbox',
    supportCategory: (category: string) => `/support/inbox/${category}`,
    messageDetails: (id: string) => `/support/inbox/${id}`,
    snippets: '/support/snippets',
    createSnippet: '/support/snippets/create',
    viewSnippet: (id: string) => `/support/snippets/${id}`,
    editSnippet: (id: string) => `/support/snippets/${id}/edit`,
    templates: '/support/templates',
    createTemplate: '/support/templates/create',
    viewTemplate: (id: string) => `/support/templates/${id}`,
    editTemplate: (id: string) => `/support/templates/${id}/edit`,
  },
};
